[package]
name = "image-to-palette"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex_color = "2.0.0"
image = "0.24.6"
